"""Constants for the vtherm_smartpi integration."""

from __future__ import annotations

from enum import Enum

DOMAIN = "vtherm_smartpi"
NAME = "Versatile Thermostat SmartPI"

CONF_TARGET_VTHERM = "target_vtherm_unique_id"
CONF_PROP_FUNCTION = "proportional_function"
CONF_MINIMAL_ACTIVATION_DELAY = "minimal_activation_delay"
CONF_MINIMAL_DEACTIVATION_DELAY = "minimal_deactivation_delay"
CONF_SMART_PI_DEADBAND = "smart_pi_deadband"
CONF_SMART_PI_HYSTERESIS_ON = "smart_pi_hysteresis_on"
CONF_SMART_PI_HYSTERESIS_OFF = "smart_pi_hysteresis_off"
CONF_SMART_PI_DEBUG = "smart_pi_debug"
CONF_SMART_PI_USE_SETPOINT_FILTER = "smart_pi_use_setpoint_filter"
CONF_SMART_PI_USE_FF3 = "smart_pi_use_ff3"
CONF_SMART_PI_RELEASE_TAU_FACTOR = "smart_pi_release_tau_factor"
CONF_SMART_PI_DEADBAND_ALLOW_P = "smart_pi_deadband_allow_p"

DEFAULT_MINIMAL_ACTIVATION_DELAY = 0
DEFAULT_MINIMAL_DEACTIVATION_DELAY = 0
DEFAULT_SMART_PI_DEADBAND = 0.05
DEFAULT_SMART_PI_HYSTERESIS_ON = 0.3
DEFAULT_SMART_PI_HYSTERESIS_OFF = 0.5
DEFAULT_SMART_PI_DEBUG = False
DEFAULT_SMART_PI_USE_SETPOINT_FILTER = True
DEFAULT_SMART_PI_USE_FF3 = False
DEFAULT_SMART_PI_RELEASE_TAU_FACTOR = 0.5
DEFAULT_SMART_PI_DEADBAND_ALLOW_P = False

DEFAULT_OPTIONS: dict[str, float | bool | int] = {
    CONF_MINIMAL_ACTIVATION_DELAY: DEFAULT_MINIMAL_ACTIVATION_DELAY,
    CONF_MINIMAL_DEACTIVATION_DELAY: DEFAULT_MINIMAL_DEACTIVATION_DELAY,
    CONF_SMART_PI_DEADBAND: DEFAULT_SMART_PI_DEADBAND,
    CONF_SMART_PI_USE_SETPOINT_FILTER: DEFAULT_SMART_PI_USE_SETPOINT_FILTER,
    CONF_SMART_PI_USE_FF3: DEFAULT_SMART_PI_USE_FF3,
    CONF_SMART_PI_HYSTERESIS_ON: DEFAULT_SMART_PI_HYSTERESIS_ON,
    CONF_SMART_PI_HYSTERESIS_OFF: DEFAULT_SMART_PI_HYSTERESIS_OFF,
    CONF_SMART_PI_RELEASE_TAU_FACTOR: DEFAULT_SMART_PI_RELEASE_TAU_FACTOR,
    CONF_SMART_PI_DEADBAND_ALLOW_P: DEFAULT_SMART_PI_DEADBAND_ALLOW_P,
    CONF_SMART_PI_DEBUG: DEFAULT_SMART_PI_DEBUG,
}

HVAC_OFF_REASON_WINDOW_DETECTION = "hvac_off_window_detection"
PROP_FUNCTION_SMART_PI = "smartpi"

DATA_FACTORY_REGISTERED = "factory_registered"
DATA_SERVICES_REGISTERED = "services_registered"

SERVICE_RESET_SMARTPI_LEARNING = "reset_smartpi_learning"
SERVICE_FORCE_SMARTPI_CALIBRATION = "force_smartpi_calibration"
SERVICE_RESET_SMARTPI_INTEGRAL = "reset_smartpi_integral"


class EventType(Enum):
    """Plugin events exposed by vtherm_smartpi."""

    SMART_PI_EVENT = "vtherm_smartpi_event"
